{ config, ... }:

let
  oos = config.lib.file.mkOutOfStoreSymlink;

  kittyConfig = ''
    # Generated by Home Manager. Put quick experiments and local overrides in
    # dotfiles/config/kitty/local.conf.

    font_family Iosevka
    font_size 13

    shell ${config.home.profileDirectory}/bin/fish

    # Linux: Alt+number. macOS: Command+number (`super` in Kitty config).
    map alt+1 goto_tab 1
    map alt+2 goto_tab 2
    map alt+3 goto_tab 3
    map alt+4 goto_tab 4
    map alt+5 goto_tab 5
    map alt+6 goto_tab 6
    map alt+7 goto_tab 7
    map alt+8 goto_tab 8
    map alt+9 goto_tab 9
    map super+1 goto_tab 1
    map super+2 goto_tab 2
    map super+3 goto_tab 3
    map super+4 goto_tab 4
    map super+5 goto_tab 5
    map super+6 goto_tab 6
    map super+7 goto_tab 7
    map super+8 goto_tab 8
    map super+9 goto_tab 9

    include local.conf
  '';

  ghosttyConfig = ''
    # Generated by Home Manager. Put quick experiments and local overrides in
    # dotfiles/config/ghostty/local.conf.

    font-family = Iosevka
    font-size = 13

    command = ${config.home.profileDirectory}/bin/fish
    shell-integration = fish

    config-file = local.conf
  '';
in
{
  # Kitty: stable cross-platform baseline from Nix; editable overlay in repo.
  xdg.configFile."kitty/kitty.conf".text = kittyConfig;
  xdg.configFile."kitty/local.conf".source =
    oos "${config.dotfiles.repoPath}/dotfiles/config/kitty/local.conf";

  # Ghostty: stable cross-platform baseline from Nix; editable overlay in repo.
  xdg.configFile."ghostty/config".text = ghosttyConfig;
  xdg.configFile."ghostty/local.conf".source =
    oos "${config.dotfiles.repoPath}/dotfiles/config/ghostty/local.conf";
}
