{ config, lib, pkgs, ... }:

let
  oos = config.lib.file.mkOutOfStoreSymlink;

  kittyTabModifier = if pkgs.stdenv.isDarwin then "super" else "alt";
  kittyTabBindings =
    lib.concatMapStringsSep "\n"
      (n: "    map ${kittyTabModifier}+${toString n} goto_tab ${toString n}")
      (lib.range 1 9);

  kittyConfig = ''
    # Generated by Home Manager. Put quick experiments and local overrides in
    # dotfiles/config/kitty/local.conf.

    font_family Iosevka
    font_size 13

    shell ${config.home.profileDirectory}/bin/fish

    # Tab switching uses the same physical key: Alt on Linux, Command on macOS.
${kittyTabBindings}

    include local.conf
  '';

  ghosttyConfig = ''
    # Generated by Home Manager. Put quick experiments and local overrides in
    # dotfiles/config/ghostty/local.conf.

    font-family = Iosevka
    font-size = 13

    command = ${config.home.profileDirectory}/bin/fish
    shell-integration = fish

    config-file = local.conf
  '';
in
{
  # Kitty: stable cross-platform baseline from Nix; editable overlay in repo.
  xdg.configFile."kitty/kitty.conf".text = kittyConfig;
  xdg.configFile."kitty/local.conf".source =
    oos "${config.dotfiles.repoPath}/dotfiles/config/kitty/local.conf";

  # Ghostty: stable cross-platform baseline from Nix; editable overlay in repo.
  xdg.configFile."ghostty/config.ghostty".text = ghosttyConfig;
  xdg.configFile."ghostty/local.conf".source =
    oos "${config.dotfiles.repoPath}/dotfiles/config/ghostty/local.conf";
}
